apiVersion: apps/v1
kind: Deployment
metadata:
  name: meido-flask
  namespace: meido
spec:
  selector:
    matchLabels:
      app: meido-flask
  template:
    metadata:
      labels:
        app: meido-flask
    spec:
      containers:
      - name: meido-flask
        image: <FLASKIMAGE>
        resources:
          limits:
            memory: "128Mi"
            cpu: "125m"
        ports:
        - containerPort: 9000
