apiVersion: apps/v1
kind: Deployment
metadata:
  name: meido
  namespace: meido
spec:
  selector:
    matchLabels:
      app: meido
  # replicas: 2
  template:
    metadata:
      labels:
        app: meido
    spec:
      containers:
        - name: meido
          image: notchman/meido-app:0.1
          resources:
            limits:
              memory: "128Mi"
              cpu: "500m"
          ports:
            - containerPort: 8080
          env:
            - name: REDIS_PATH
              value: "redis:6379"
            - name: "PORT"
              value: "8080"
